title: N.otes
description: Nick Belzer's Notes.

defaults:
  - scope:
      path: ""
    values:
       layout: "default"

collections:
  pages:
    output: true
    permalink: /:collection/:path/
    sort_by: last_modified

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag