title: N.otes
description: Nick Belzer's Notes.

defaults:
  - scope:
      path: ""
    values:
       layout: "default"
  - scope:
      path: "topics"
    values:
      layout: "topic"

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag